language: python
cache: pip
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest
jobs:
  include:
    - name: Run unit tests
      stage: test
      script:
        - pytest
      python:
        - "3.5"
        - "3.6"
        - "3.7"
    - name: Check formatting
      stage: test
      install:
        - pip install black
      script:
        - black --check .
      python:
        - "3.7"
